---
######## Git
- name: Install Git
  become: yes
  pacman: name=git state=present

- name: Create Git config symlink
  file:
    src: '{{ playbook_dir }}/roles/common/files/.gitconfig'
    dest: ~/.gitconfig
    state: link

######## NeoVim
- name: Install NeoVim
  become: yes
  pacman: name=neovim state=present

- name: Check NeoVim config dir state
  stat: path=~/.config/nvim
  register: nvim

- name: Remove NeoVim config if it is a dir
  file: path=~/.config/nvim state=absent
  when: nvim.stat.isdir is defined and nvim.stat.isdir

- name: Create NeoVim config symlink
  file:
    src: '{{ playbook_dir }}/roles/common/files/nvim'
    dest: ~/.config/nvim
    state: link
    force: yes

######## Bash aliases
- name: Create symlink to .bash_aliases
  file:
    src: '{{ playbook_dir }}/roles/common/files/.bash_aliases'
    dest: ~/.bash_aliases
    state: link
    force: yes

- name: Source .bash_aliases from .bashrc
  lineinfile:
    path: ~/.bashrc
    line: source ~/.bash_aliases
    state: present

######## Docker and docker-compose
- name: Ensure docker is installed
  become: yes
  pacman: name=docker state=latest

- name: Ensure docker-compose is installed
  become: yes
  pacman: name=docker-compose state=latest

- name: Ensure Docker daemon is started and enabled
  become: yes
  service:
    name: docker
    enabled: yes
    state: started

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Ensure user vsobotka is int he docker group
  become: yes
  user:
    user: vsobotka
    groups: docker
    append: yes

######## Spacemacs
- name: Ensure emacs is installed
  become: yes
  pacman: name=emacs state=latest

- name: Ensure spacemacs repo is cloned
  git:
    repo: "https://github.com/syl20bnr/spacemacs"
    dest: "~/.emacs.d"
    clone: yes
    force: no
    accept_hostkey: yes

- name: Create spacemacs config symlink
  file:
    src: '{{ playbook_dir }}/roles/common/files/.spacemacs'
    dest: ~/.spacemacs
    state: link
    force: yes

######## Vim-plug
- name: Ensure directory structure for vim-plug exists
  file: path=~/.local/share/nvim/site/autoload state=directory

- name: Ensure vim-plug is downloaded
  get_url: 
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim    

######## Firefox
- name: Ensure Firefox is installed
  become: yes
  pacman: name=firefox state=latest

######## Spotify
- name: Ensure Spotify is installed
  command: yaourt -S spotify --noconfirm --needed

######## Visual Studio Code
- name: Ensure Visual Studio Code is installed
  command: yaourt -S visual-studio-code-bin --noconfirm --needed

