---
- name: Install Git
  become: yes
  pacman: name=git state=present

- name: Create Git config symlink
  file:
    src: '{{ playbook_dir }}/roles/common/files/.gitconfig'
    dest: ~/.gitconfig
    state: link

- name: Install NeoVim
  become: yes
  pacman: name=neovim state=present

- name: Check NeoVim config dir state
  stat: path=~/.config/nvim
  register: nvim

- name: Remove NeoVim config if it is a dir
  file: path=~/.config/nvim state=absent
  when: nvim.stat.isdir is defined and nvim.stat.isdir

- name: Create NeoVim config symlink
  file:
    src: '{{ playbook_dir }}/roles/common/files/nvim'
    dest: ~/.config/nvim
    state: link
    force: yes

- name: Create symlink to .bash_aliases
  file:
    src: '{{ playbook_dir }}/roles/common/files/.bash_aliases'
    dest: ~/.bash_aliases
    state: link
    force: yes

- name: Source .bash_aliases from .bashrc
  lineinfile:
    path: ~/.bashrc
    line: source ~/.bash_aliases
    state: present

